//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sim_Library.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hd
    {
        public Hd()
        {
            this.HdCt = new HashSet<HdCt>();
        }
    
        public int MaHd { get; set; }
    
        public virtual ICollection<HdCt> HdCt { get; set; }
    }
}
