//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sim_Library.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class HdDkCt
    {
        public HdDkCt()
        {
            this.Sim = new HashSet<Sim>();
        }
    
        public int MaHkDk { get; set; }
        public int MaKh { get; set; }
    
        public virtual HdDk HdDk { get; set; }
        public virtual Kh Kh { get; set; }
        public virtual ICollection<Sim> Sim { get; set; }
    }
}
