//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sim_Library.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kh
    {
        public Kh()
        {
            this.HdCt = new HashSet<HdCt>();
            this.HdDkCt = new HashSet<HdDkCt>();
        }
    
        public int MaKh { get; set; }
        public string TenKh { get; set; }
        public string NgheNghiep { get; set; }
        public string ChucVu { get; set; }
        public string DiaChi { get; set; }
    
        public virtual ICollection<HdCt> HdCt { get; set; }
        public virtual ICollection<HdDkCt> HdDkCt { get; set; }
    }
}
