//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sim_Library.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sim
    {
        public Sim()
        {
            this.Sd = new HashSet<Sd>();
        }
    
        public int MaSim { get; set; }
        public string SoSim { get; set; }
        public Nullable<int> MaHdDk { get; set; }
        public Nullable<int> MaKh { get; set; }
    
        public virtual HdDk HdDk { get; set; }
        public virtual ICollection<Sd> Sd { get; set; }
    }
}
