//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sim_Library.DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SimDBContext : DbContext
    {
        public SimDBContext()
            : base("name=SimDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Hd> Hd { get; set; }
        public DbSet<HdDk> HdDk { get; set; }
        public DbSet<Kh> Kh { get; set; }
        public DbSet<Sd> Sd { get; set; }
        public DbSet<Sim> Sim { get; set; }
    }
}
