<%@ Page Title="KhachHang" Theme="Sim" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="~/pages/KhachHang.aspx.cs" Inherits="Sim_Web.pages.KhachHang" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <div class="row">
        <div class="col-xs-6">
            <div>
                <div class="form-group">
                    <label class="control-label">Họ tên</label>
                    <asp:TextBox ID="txtHoTen" runat="server" CssClass="form-control"></asp:TextBox>

                </div>
                <div class="form-group">
                    <label class="control-label">Nghề nghiệp</label>
                    <asp:TextBox ID="txtNgheNhgiep" runat="server" CssClass="form-control"></asp:TextBox>
                </div>

                <div class="form-group">
                    <label class="control-label">Chức vụ</label>
                    <asp:TextBox ID="txtChucVu" runat="server" CssClass="form-control"></asp:TextBox>
                </div>
                <div class="form-group">
                    <label class="control-label">Địa chỉ</label>
                    <asp:TextBox ID="txtDiaChi" runat="server" CssClass="form-control"></asp:TextBox>
                </div>

                <asp:Label runat="server" ID="lbShowStatus"></asp:Label>
                <asp:Button runat="server" ID="btnDangKy" SkinID="btnPrimary" Text="Đăng ký" OnClick="btnDangKy_Click" />
                <asp:Button runat="server" ID="btnClear" Text="Làm mới" CssClass="btn btn-danger" OnClick="btnClear_Click" />
            </div>
        </div>
        <div class="col-xs-6">
            <div class="lead">Danh sách khách hàng</div>
            <asp:GridView runat="server" id="gvKh"  AutoGenerateDeleteButton="True" AutoGenerateSelectButton="True" AutoGenerateColumns="False" CssClass="table table-bordered" OnRowDeleting="gvKh_RowDeleting" OnSelectedIndexChanging="gvKh_SelectedIndexChanging">
                
                
                <Columns>
                    <asp:BoundField DataField="MaKh" HeaderText="MaKh" />
                    <asp:BoundField DataField="TenKh" HeaderText="TenKh" />
                    <asp:BoundField DataField="NgheNghiep" HeaderText="NgheNghiep" />
                    <asp:BoundField DataField="ChucVu" HeaderText="ChucVu" />
                    <asp:BoundField DataField="DiaChi" HeaderText="DiaChi" />
                </Columns>
                
            </asp:GridView>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-6 col-xs-offset-6">
            
            <div class="lead">Danh sách sim</div>
            <asp:GridView runat="server" ID="gvSims" CssClass="table table-bordered" OnSelectedIndexChanging="gvSims_SelectedIndexChanging"></asp:GridView>
        </div>
    </div>
</asp:Content>
